### ISSUE TITLE
Request: Ability to format Descriptions better

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#10]
Currently, if I try to add extra blank lines to the Description, it doesn't put text further down, but seems to do nothing. It'd be nice to be able to do some standard formatting and have it more WYSWEIWYG (What you see while editing is what you get)

Maybe you could add Bold Italics and font sizes via buttons eventually?

Spacing and the ability to separate information is the big thing here. It doesn't have to be MS Word, but some basic formatting will go a long way.
http://screencast.com/t/rYCavwpYvsZ

**Comment by cameronsutter** [comment]
So, the descriptions support markdown syntax which you can learn about here: https://daringfireball.net/projects/markdown/syntax but the app doesn't say that anywhere, so that's something I should fix
