### ISSUE TITLE
Timeline view: When zoomed, clicking on a card doesn't open the card

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#107]
Steps to repro:
1. On Timeline view, pick a zoom level and zoom in or out
2. Try clicking on a card.

Result:
The screen reverts back to normal view. Clicking on the card now will actually open it up.
Found in v.0.9

**Comment by cameronsutter** [comment]
This might be intended behavior. i remember talking about this when we first made it. We should review it

**Comment by cameronsutter** [comment]
Fixed in a recent commit
