### ISSUE TITLE
Undo log: Edit a card then hit undo, then edit the card again and the undo log doesn't add another edit action to undo

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#121]
1. Have a card
2. Edit the card.
3. Click Undo.
4. Note that the change is undone.
5. Edit the card again.
6. Click Undo.

Results: Notice that there is no edit card action to undo again. You have a redo on the stack last. If you redo and undo, it undoes your change though. It's just not working like I expected.

**Comment by cameronsutter** [comment]
I just want to confirm we're seeing the same thing. Are you seeing the item on the list of changes disappear?
