### ISSUE TITLE
Character/Place tags can't be added to cards via the + popup menu

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#122]
1. Add a few characters and places to a project
2. Add a card to a storyline.
3. With the card open, click the hover + on the Character or Place section on the right side of the screen. 
4. When the popup menu appears, try clicking one of your characters or places.

Result: Clicking doesn't seem to do anything.
I found out that tags work at least. I can add tags.

**Comment by cameronsutter** [comment]
This wasn't the bug that I mentioned to you that i fixed, but I'm still not able to reproduce it
