### ISSUE TITLE
Remove Show Dev Tools. Replace with Debug functionality

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#217]
Seems like not very useful for customer. Maybe make a debug flag for yourself instead and when you set the flag, tools like this pop up in the menus? Turn of the flag after done. Or you could have a special shortcut that opens debug tools? I dunno. Having it customer facing seems like bad form.

**Comment by cameronsutter** [comment]
Fixed with [b72a96](https://github.com/cameronsutter/plottr_electron/commit/b72a963235fdbe4951add86737cde04739c73dd4)
