### ISSUE TITLE
Characters: Editing and saving a character gives the impression you lost your data

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#220]
1. Create a character.
2. Edit the character and hit save
Result: Although the character was saved, it now shows a new character form, so it feels like you lost your data. If you close the form and go back to your character, it shows it was saved. But this is clunky! Should remain on the character you are editing so you can see your changes. See video:

https://cl.ly/341r2e451L2N

**Comment by cameronsutter** [comment]
Cannot reproduce. If you can repro it again, I'll reopen
