### ISSUE TITLE
Template improvements: Let's make templates their own file type

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#226]
Templates could use some love. Right now, you can load one up and overwrite it, and the only way to get it back is to re-download it.

So, here are some suggestions  of AC to make templates great again:

1) Create a new plottr template file type.
2) When someone opens a template file and tries to save over it, they are asked if they'd like to save a copy as a new file. They can make changes to a template if they wish, but if they are just trying to make a new file based off that template, we don't want to overwrite the template accidentally. This helps stop accidental overwriting.
3) We should allow users to create their own templates, much like scrivener does, so they can base new stories off a template they've customized for themselves. This means you should allow  them to base a template off another template (perhaps a 7 point template with an extra point? :)
4) the feature should be natural, act just like file saving, just that you now have two formats (Think Microsoft word. You can save files as multiple types, such as doc, docx, well we can choose to save plottr files as pltr or ptpt or whatever we call it.

**Comment by cameronsutter** [comment]
fixed with advanced templates
