### ISSUE TITLE
Undo deletions do not restore cards

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#241]
1. Create a card named "Order"
2. Delete the card
3. Create another card named "Order 2"
4. Undo the deletion of "Order"

Result: Order is never restored. We're all gonna fall into anarchy!

**Comment by cameronsutter** [comment]
Use this for better undo functionality: https://github.com/benjamine/jsondiffpatch

**Comment by cameronsutter** [comment]
going to be fixed when i fix undo
