### ISSUE TITLE
Outline tab: Filtering by Main Plot does not filter out other story lines

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#271]
1. have at least two story lines with a few scenes.
2. Go to the Outline tab.
3. Filter by story line.
4. Choose the Main Plot.

Results: Other story lines are not filtered out when you select Main Plot as your filter. However, if you filter by those story lines, main plot scenes do get filtered out.

**Comment by cameronsutter** [comment]
fixed!
