### ISSUE TITLE
Scrolling in card edit scrolls timeline in background

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#272]
1. Create a new card.
2. Edit the card.
3. Scroll up and down in the card and look at the background where the timeline is.

Result: The timeline is scrolling alongside the card.
Also, I noticed that by default, parts of the card are off screen because the elements don't all fit in the window. Maybe that's why this issue exists. Scrolling is enabled on the card.

offscreen text: https://cl.ly/3ddc7ab450cb

**Comment by cameronsutter** [comment]
fixed!
