### ISSUE TITLE
Zooming + click to zoom in and center on a card

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#29]
So, on large projects, viewing the big picture or navigating to far off cards is hard. How about we add a zoom in and zoom out feature so we can see all our structure, and then maybe make it so you can double click or do some other shortcut combo on a card in order to zoom into that part of your structure and center yourself there? 

This would make navigation very much easier.

**Comment by cameronsutter** [comment]
use this module http://electron.atom.io/docs/v0.36.7/api/web-frame/
