### ISSUE TITLE
Add Right-click menu for copy and paste

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#9]
For users of Mac and Windows (like me) Right click menus are one of the essential forms of happiness!

**Comment by cameronsutter** [comment]
http://electron.atom.io/docs/v0.36.7/api/menu/#menupopupbrowserwindow-x-y-positioningitem

**Comment by cameronsutter** [comment]
maybe also https://github.com/parro-it/electron-contextmenu-middleware
